
version: '3.1'

services:
  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/var/www/authed-buildings.example.com:ro
    extra_hosts:
      - "authed-buildings.example.com:192.168.0.26"
  api:
    build: backend/.
    volumes:
      - ./docker/settings.yml:/settings.yml:ro
    depends_on:
      - db
    ports:
      - 8001:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: buildings_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_user_password
    ports:
      - 5432:5432
